name: Tag Latest Release Images and Deploy to Production

on:
  release:
    types: [ released ]


jobs:
  build-production:
    name: Build production ${{ github.event.release.tag_name }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-production.yml@fixing-workflows
    with:
      image_name: ${{ vars.IMAGE_NAME }}
      tag: ${{ github.event.release.tag_name }}
    secrets: inherit
