name: Build latest from main and AutoDeploy to Testing and Staging

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    name: Build ${{ github.sha }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@main
    with:
      image_name: ${{ vars.IMAGE_NAME }}
    secrets: inherit

  deploy:
    needs: build
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@main
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}-unstable:${{ github.sha }}
      payload_template: .github/data/build-main.json
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_KEY }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
      commit_subject: Update unset-acq-tag image to ${{ github.sha }}
    secrets: inherit
