name: Build latest from main and AutoDeploy to Workshop

on:
  workflow_run:
    workflows: [ 'Run Tests' ]
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build-unstable:
    name: Build unstable ${{ github.sha }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: mlibrary/platform-engineering-workflows/.github/workflows/build-unstable.yml@main
    with:
      image_name: ${{ vars.IMAGE_NAME }}
    secrets: inherit

  deploy:
    needs: build-unstable
    uses: mlibrary/platform-engineering-workflows/.github/workflows/deploy.yml@v1
    with:
      image: ghcr.io/mlibrary/${{ vars.IMAGE_NAME }}-unstable:${{ github.sha }}
      file: environments/unset-acq-tags/app-image.txt
      CONFIG_REPO_RW_APP_ID: ${{ vars.CONFIG_REPO_RW_KEY }}
      CONFIG_REPO_RW_INSTALL_ID: ${{ vars.CONFIG_REPO_RW_INSTALL_ID }}
      CONFIG_REPO_FULL_NAME: ${{ vars.CONFIG_REPO_FULL_NAME }}
    secrets: inherit
